### ISSUE TITLE
syntax and output error according to the log

### ISSUE THREAD

**Issue by ghost** [ToxicWaveHD/Minimal-Fetch#1]
**I installed it according to the guide, judging by readme.md. But when starting it writes a syntax error and it infuriates**
![Fail](https://github.com/ToxicWaveHD/Minimal-Fetch/assets/157636018/70e014d4-000e-457b-8d08-e7672f1bfb96)

**Comment by MannuVilasara** [comment]
same issue

**Comment by ToxicWaveHD** [comment]
@FarParticul Should be fixed now thanks to [MannuVilasara](https://github.com/MannuVilasara)'s handy work :D

**Comment by ghost** [comment]
> @FarParticul Should be fixed now thanks to [MannuVilasara](https://github.com/MannuVilasara)'s handy work :D

Okay, thank you!
