### ISSUE TITLE
Fetch output bug

### ISSUE THREAD

**Issue by ghost** [ToxicWaveHD/Minimal-Fetch#4]
## Description
**When outputting an image, I understand the text of the image itself is output.**
## Specs
**OS: Void GNU/Linux (glibc)
Terminal emulator: kitty
dependencies: everyone's standing**
## Screenshot
![image](https://github.com/ToxicWaveHD/Minimal-Fetch/assets/157636018/430f75a8-2430-4502-9454-bbc8067a745b)

**Comment by ToxicWaveHD** [comment]
Looks like you are using an older version of the code.

Try installing this instead:
https://github.com/ToxicWaveHD/Minimal-Fetch/releases/tag/mfetch2

**Comment by ghost** [comment]
> Looks like you are using an older version of the code.
> 
> Try installing this instead: https://github.com/ToxicWaveHD/Minimal-Fetch/releases/tag/mfetch2

![image](https://github.com/ToxicWaveHD/Minimal-Fetch/assets/157636018/bd9a8eb4-655f-47b4-81d1-9429fd8f0325)

**Comment by ghost** [comment]
I just looked it up, I did it wrong

**Comment by ToxicWaveHD** [comment]
Cool, tell me if you have any other issues.

**Comment by ghost** [comment]
all right. And I also want to say that the respect to you for such a fetch, probably already saw my rice in discord(I know you liked :) ). I recently went to gnu/linux void and this problem appeared.
