### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ghost** [ToxicWaveHD/Minimal-Fetch#5]
# Description
Good evening/afternoon, I was wondering through which program you make icons, and is there any example file to create your logo?

**Comment by ghost** [comment]
And was wondering how the picture should be made and how many pixels?

**Comment by ghost** [comment]
I already made the logo, so I'm gonna close the thread because I found a solution.

**Comment by ToxicWaveHD** [comment]
Hey, sorry to get to you so late

**Comment by ToxicWaveHD** [comment]
I usually use a program called Pixelorama, (great for all things pixel art)

As a rough guide regular logo images should be 24x24px, and logo-big images should be 32x32px, also solid colours are preferable.

**Comment by ghost** [comment]
> Hey, sorry to get to you so late

It's okay. I know you had exams.) (I'm 15 too, but the main state exam isn't until winter. ОГЭ)

**Comment by ghost** [comment]
> I usually use a program called Pixelorama, (great for all things pixel art)
> 
> As a rough guide regular logo images should be 24x24px, and logo-big images should be 32x32px, also solid colours are preferable.

I just started making a logo on it, do you mind if I send it to you in discord?

**Comment by ToxicWaveHD** [comment]
Sure ig
